# Generated by Django 5.0.2 on 2024-02-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_assets', '0002_remove_assetlog_employee_assetlog_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
    ]
